"""Migração inicial

Revision ID: bd476f3cd926
Revises: 
Create Date: 2024-09-11 13:39:38.117223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd476f3cd926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_livro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro')
    # ### end Alembic commands ###
